---
abstract: 'Load Tcl/Tk-Library to Temp-Directory'
author:
  - 'Jürgen von Brietzke <brietzkej@t-online.de>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tkx-TclTk-Bind
no_index:
  directory:
    - t
    - inc
requires:
  Archive::Tar: 0
  Const::Fast: 0
  English: 0
  Exporter: 0
  File::Remove: 0
  File::Spec: 0
  Tkx: 0
version: v1.0.00
